apiVersion: build.openshift.io/v1
kind: Build
metadata:
  annotations:
    openshift.io/build-config.name: springboot-docker
    openshift.io/build.number: "1"
    openshift.io/build.pod-name: springboot-docker-1-build
  creationTimestamp: "2024-03-15T17:04:08Z"
  generation: 2
  labels:
    app: springboot-docker
    app.kubernetes.io/component: springboot-docker
    app.kubernetes.io/instance: springboot-docker
    buildconfig: springboot-docker
    openshift.io/build-config.name: springboot-docker
    openshift.io/build.start-policy: Serial
  name: springboot-docker-1
  namespace: arij-project
  ownerReferences:
  - apiVersion: build.openshift.io/v1
    controller: true
    kind: BuildConfig
    name: springboot-docker
    uid: 75d96d93-f5ec-4836-92d7-efe7e7a0602d
  resourceVersion: "9403719"
  uid: 11a26070-5bbf-4c4b-bac6-1d0bcb7d159c
spec:
  nodeSelector: null
  output:
    pushSecret:
      name: builder-dockercfg-rk5b5
    to:
      kind: ImageStreamTag
      name: springboot-docker:latest
  postCommit: {}
  resources: {}
  revision:
    git:
      author:
        email: 118684147+arijknani@users.noreply.github.com
        name: arijknani
      commit: ad46ca1c1620e3b3d327ff02b2f6c24bbc3f5c98
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update README.md
    type: Git
  serviceAccount: builder
  source:
    git:
      ref: docker-build
      uri: https://github.com/arijknani/containerized-app.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: openjdk@sha256:fe05457a5e9b9403f8e72eeba507ae80a4237d2d2d3f219fa62ceb128482a9ee
    type: Docker
  triggeredBy:
  - imageChangeBuild:
      fromRef:
        kind: ImageStreamTag
        name: openjdk:latest
        namespace: arij-project
      imageID: openjdk@sha256:fe05457a5e9b9403f8e72eeba507ae80a4237d2d2d3f219fa62ceb128482a9ee
    message: Image change
status:
  completionTimestamp: "2024-03-15T17:10:10Z"
  conditions:
  - lastTransitionTime: "2024-03-15T17:04:10Z"
    lastUpdateTime: "2024-03-15T17:04:10Z"
    status: "False"
    type: New
  - lastTransitionTime: "2024-03-15T17:04:13Z"
    lastUpdateTime: "2024-03-15T17:04:13Z"
    status: "False"
    type: Pending
  - lastTransitionTime: "2024-03-15T17:10:10Z"
    lastUpdateTime: "2024-03-15T17:10:10Z"
    status: "False"
    type: Running
  - lastTransitionTime: "2024-03-15T17:10:10Z"
    lastUpdateTime: "2024-03-15T17:10:10Z"
    status: "True"
    type: Complete
  config:
    kind: BuildConfig
    name: springboot-docker
    namespace: arij-project
  duration: 360000000000
  output:
    to:
      imageDigest: sha256:1cdb8edcba482d1892874ac4864620f0af736ae33ad15f53cb4cff00ed1ee201
  outputDockerImageReference: image-registry.openshift-image-registry.svc:5000/arij-project/springboot-docker:latest

